 package CapaPresentacio;

import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Graphics;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author pol
 */


public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    private int x = -1;
    private int y  = -1;
    private boolean linea2punts;
    private CtrlPresentacio cp = new CtrlPresentacio();
    private boolean active = true;
    private boolean activeList = true;
   
    private int snom;
    
    private ArrayList<Integer> Relacions = new ArrayList<Integer>();
    private ArrayList<String> ListNoms = new ArrayList<String>();
     ArrayList<Integer> adjac = new ArrayList<Integer>();
    
    private int numRelations;
    private int actual;
    private int actualRelation;
    public Vista() {
        initComponents();
        setResizable(false);
        MutePanel.setVisible(false);
        setVisible(true);
        PanelNewRelation.setVisible(false);
        BorrarEditar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        javax.swing.ButtonGroup buttonGroup6 = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        PANELS = new javax.swing.JTabbedPane();
        PanelPrincipal = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel() {
            public void paint(Graphics g)  {
                super.paint(g);
                cpaint(g);
            }
        };
        IMAGEN = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ButtonSolve = new javax.swing.JButton();
        LabelSeleccio = new javax.swing.JLabel();
        RadioGenetic = new javax.swing.JRadioButton();
        RadioAnnealing = new javax.swing.JRadioButton();
        PanelNewElement = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        NomElement = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        SaveNewElement = new javax.swing.JButton();
        ProgresBar = new javax.swing.JProgressBar();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        AddRelation = new javax.swing.JButton();
        NomElementRelacio = new javax.swing.JTextField();
        NumRelacions = new javax.swing.JTextField();
        Spinner = new javax.swing.JSpinner();
        textxy = new javax.swing.JTextField();
        CancelButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextSolution = new javax.swing.JTextArea();
        CostText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        info = new javax.swing.JTextField();
        PanelOpcions = new javax.swing.JPanel();
        TabAnealing = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CoolingFactor = new javax.swing.JTextField();
        InitialTemperature = new javax.swing.JTextField();
        StopConditionAnealing = new javax.swing.JTextField();
        Random = new javax.swing.JRadioButton();
        TwoAp = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        MutateLittle = new javax.swing.JRadioButton();
        MutateRate = new javax.swing.JRadioButton();
        MutePanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        MutationRateVar = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        MutationSwap = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Jlabel3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        StopCondition = new javax.swing.JTextField();
        NG = new javax.swing.JTextField();
        NT = new javax.swing.JTextField();
        TournamentSize = new javax.swing.JTextField();
        MutationRate = new javax.swing.JTextField();
        Roulettesi = new javax.swing.JRadioButton();
        Rouletteno = new javax.swing.JRadioButton();
        ElitismSi = new javax.swing.JRadioButton();
        Elitismno = new javax.swing.JRadioButton();
        Edgesi = new javax.swing.JRadioButton();
        Edgeno = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        Mutate1 = new javax.swing.JRadioButton();
        Mutat2 = new javax.swing.JRadioButton();
        Mutat3 = new javax.swing.JRadioButton();
        MS = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        PanelElement = new javax.swing.JPanel();
        PanelElements = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextRelations = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        ElementsInactius = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList();
        BorrarEditar = new javax.swing.JPanel();
        DeleteButton = new javax.swing.JButton();
        CheckBoxDesactivar = new javax.swing.JCheckBox();
        Editar = new javax.swing.JButton();
        PanelNewRelation = new javax.swing.JPanel();
        SpinnerNewRelation = new javax.swing.JSpinner();
        ButtonNewRelation = new javax.swing.JButton();
        TextNewRelation = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        CarregarDades = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuHelp = new javax.swing.JMenu();
        Ajuda = new javax.swing.JMenuItem();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelPrincipalMouseClicked(evt);
            }
        });

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        IMAGEN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        IMAGEN.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacio/BCN.jpg"))); // NOI18N
        IMAGEN.setEnabled(false);
        IMAGEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IMAGENMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IMAGEN, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IMAGEN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );

        ButtonSolve.setText("Solve");
        ButtonSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSolveActionPerformed(evt);
            }
        });

        LabelSeleccio.setText("Selecciona algoritme");

        RadioGenetic.setText("Genetic");
        RadioGenetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioGeneticActionPerformed(evt);
            }
        });

        RadioAnnealing.setText("Simulated Annealing");
        RadioAnnealing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioAnnealingActionPerformed(evt);
            }
        });

        PanelNewElement.setBackground(new java.awt.Color(204, 204, 204));
        PanelNewElement.setBorder(new javax.swing.border.MatteBorder(null));
        PanelNewElement.setForeground(new java.awt.Color(102, 102, 102));
        PanelNewElement.setEnabled(false);

        jLabel15.setText("Nou Paquet");

        jLabel16.setText("Nom");

        jLabel17.setText("Distància ");

        SaveNewElement.setText("Guardar");
        SaveNewElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNewElementActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Complet");

        jLabel18.setText("Relació amb paquet");

        AddRelation.setText("Add");
        AddRelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRelationActionPerformed(evt);
            }
        });

        NomElementRelacio.setEditable(false);

        NumRelacions.setEditable(false);

        textxy.setEditable(false);
        textxy.setText("xy = ");
        textxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textxyActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancelar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        PanelNewElement.setVisible(false);

        javax.swing.GroupLayout PanelNewElementLayout = new javax.swing.GroupLayout(PanelNewElement);
        PanelNewElement.setLayout(PanelNewElementLayout);
        PanelNewElementLayout.setHorizontalGroup(
            PanelNewElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNewElementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNewElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNewElementLayout.createSequentialGroup()
                        .addComponent(NumRelacions, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SaveNewElement)
                        .addGap(10, 10, 10))
                    .addGroup(PanelNewElementLayout.createSequentialGroup()
                        .addGroup(PanelNewElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(PanelNewElementLayout.createSequentialGroup()
                                .addComponent(ProgresBar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox1))
                            .addGroup(PanelNewElementLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel17))
                            .addGroup(PanelNewElementLayout.createSequentialGroup()
                                .addComponent(NomElementRelacio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddRelation)))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(PanelNewElementLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NomElement, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textxy, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        PanelNewElementLayout.setVerticalGroup(
            PanelNewElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNewElementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelNewElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(textxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelNewElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNewElementLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PanelNewElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelNewElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddRelation)
                            .addComponent(NomElementRelacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelNewElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox1)
                            .addComponent(ProgresBar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(NumRelacions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNewElementLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelNewElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaveNewElement)
                            .addComponent(CancelButton))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ButtonSolve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelNewElement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(LabelSeleccio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RadioGenetic)
                                .addGap(12, 12, 12)
                                .addComponent(RadioAnnealing)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioAnnealing)
                    .addComponent(LabelSeleccio)
                    .addComponent(RadioGenetic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonSolve, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelNewElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        TextSolution.setEditable(false);
        TextSolution.setColumns(20);
        TextSolution.setRows(1);
        jScrollPane3.setViewportView(TextSolution);

        CostText.setEditable(false);

        jLabel12.setText("Tour");

        jLabel14.setText("Cost");

        info.setEditable(false);
        info.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        info.setMaximumSize(new java.awt.Dimension(298, 28));
        info.setMinimumSize(new java.awt.Dimension(298, 28));
        info.setPreferredSize(new java.awt.Dimension(298, 28));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(CostText, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CostText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PANELS.addTab("Vista Principal", PanelPrincipal);

        jLabel7.setText("Temperatura Inicial:");

        jLabel8.setText("Factor Refredament:");

        jLabel9.setText("Condició de Parada:");

        CoolingFactor.setText("0.03");

        InitialTemperature.setText("1000");

        StopConditionAnealing.setText("1000");

        Random.setText("Random");
        Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomActionPerformed(evt);
            }
        });

        TwoAp.setSelected(true);
        TwoAp.setText("TwoAp");
        TwoAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoApActionPerformed(evt);
            }
        });

        jLabel20.setText("Solució Inicial:");

        jLabel21.setText("Mutació:");

        MutateLittle.setSelected(true);
        MutateLittle.setText("TwoOpt");
        MutateLittle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MutateLittleActionPerformed(evt);
            }
        });

        MutateRate.setText("Rate");
        MutateRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MutateRateActionPerformed(evt);
            }
        });

        MutePanel.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel22.setText("Mutation Rate:");

        MutationRateVar.setText("0.15");

        jLabel23.setText("Mutation Swap:");

        MutationSwap.setText("0.9");

        javax.swing.GroupLayout MutePanelLayout = new javax.swing.GroupLayout(MutePanel);
        MutePanel.setLayout(MutePanelLayout);
        MutePanelLayout.setHorizontalGroup(
            MutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MutePanelLayout.createSequentialGroup()
                .addGroup(MutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MutationRateVar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(MutationSwap)))
        );
        MutePanelLayout.setVerticalGroup(
            MutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MutePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(MutationRateVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(MutationSwap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MutePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(MutateRate)
                                .addGap(18, 18, 18)
                                .addComponent(MutateLittle))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Random)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TwoAp))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(InitialTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CoolingFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(StopConditionAnealing, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(576, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(InitialTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CoolingFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(StopConditionAnealing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Random)
                    .addComponent(TwoAp))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(MutateLittle)
                    .addComponent(MutateRate))
                .addGap(18, 18, 18)
                .addComponent(MutePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        TabAnealing.addTab("Anealing", jPanel2);

        Jlabel3.setText("Stop Condition:");

        Label4.setText("Number of Generations:");

        jLabel1.setText("Elitism:");

        jLabel2.setText("Number of Tours:");

        jLabel3.setText("Roulette Wheel:");

        jLabel4.setText("Tournament Size:");

        jLabel5.setText("Edge Crossover:");

        jLabel6.setText("Mutation Rate:");

        StopCondition.setText("20");

        NG.setText("1000");

        NT.setText("50");

        TournamentSize.setText("5");

        MutationRate.setText("0.15");

        Roulettesi.setSelected(true);
        Roulettesi.setText("Si");
        Roulettesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoulettesiActionPerformed(evt);
            }
        });

        Rouletteno.setText("No");
        Rouletteno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoulettenoActionPerformed(evt);
            }
        });

        ElitismSi.setSelected(true);
        ElitismSi.setText("Si");
        ElitismSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElitismSiActionPerformed(evt);
            }
        });

        Elitismno.setText("No");
        Elitismno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElitismnoActionPerformed(evt);
            }
        });

        Edgesi.setSelected(true);
        Edgesi.setText("Si");
        Edgesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdgesiActionPerformed(evt);
            }
        });

        Edgeno.setText("No");
        Edgeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdgenoActionPerformed(evt);
            }
        });

        jLabel24.setText("Mutate: ");

        Mutate1.setText("Rate");
        Mutate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mutate1ActionPerformed(evt);
            }
        });

        Mutat2.setText("Swap Rate");
        Mutat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mutat2ActionPerformed(evt);
            }
        });

        Mutat3.setSelected(true);
        Mutat3.setText("TwoOpt");
        Mutat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mutat3ActionPerformed(evt);
            }
        });

        MS.setText("0.9");

        jLabel25.setText("Mutation Swap:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(45, 45, 45))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Mutate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mutat3)
                                .addGap(5, 5, 5)
                                .addComponent(Mutat2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Roulettesi, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Edgesi, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ElitismSi, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Elitismno)
                                    .addComponent(Rouletteno)
                                    .addComponent(Edgeno)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(Jlabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StopCondition, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(NG, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(NT, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MutationRate, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel25))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MS, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TournamentSize, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel3)
                    .addComponent(StopCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(MutationRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label4)
                    .addComponent(NG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TournamentSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ElitismSi)
                        .addComponent(Elitismno)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Roulettesi)
                    .addComponent(Rouletteno))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edgeno)
                    .addComponent(Edgesi)
                    .addComponent(jLabel5))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mutate1)
                    .addComponent(jLabel24)
                    .addComponent(Mutat2)
                    .addComponent(Mutat3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabAnealing.addTab("Genetic", jPanel1);

        javax.swing.GroupLayout PanelOpcionsLayout = new javax.swing.GroupLayout(PanelOpcions);
        PanelOpcions.setLayout(PanelOpcionsLayout);
        PanelOpcionsLayout.setHorizontalGroup(
            PanelOpcionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabAnealing, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        PanelOpcionsLayout.setVerticalGroup(
            PanelOpcionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionsLayout.createSequentialGroup()
                .addComponent(TabAnealing, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PANELS.addTab("Opcions Algoritmes", PanelOpcions);

        PanelElements.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel10.setText("LLista de Paquets Actius");

        jLabel11.setText("  Llista de Paquets Eliminats");

        jLabel19.setText("Relacions");

        TextRelations.setEditable(false);
        TextRelations.setColumns(20);
        TextRelations.setRows(5);
        jScrollPane6.setViewportView(TextRelations);

        ElementsInactius.setEditable(false);
        ElementsInactius.setColumns(20);
        ElementsInactius.setRows(5);
        jScrollPane8.setViewportView(ElementsInactius);

        List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(List);

        DeleteButton.setText("Borrar");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        CheckBoxDesactivar.setText("Desactivar tots");

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        PanelNewRelation.setEnabled(false);

        ButtonNewRelation.setText("Add");
        ButtonNewRelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNewRelationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNewRelationLayout = new javax.swing.GroupLayout(PanelNewRelation);
        PanelNewRelation.setLayout(PanelNewRelationLayout);
        PanelNewRelationLayout.setHorizontalGroup(
            PanelNewRelationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNewRelationLayout.createSequentialGroup()
                .addComponent(TextNewRelation, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SpinnerNewRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonNewRelation)
                .addGap(36, 36, 36))
        );
        PanelNewRelationLayout.setVerticalGroup(
            PanelNewRelationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNewRelationLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelNewRelationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerNewRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNewRelation)
                    .addComponent(TextNewRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BorrarEditarLayout = new javax.swing.GroupLayout(BorrarEditar);
        BorrarEditar.setLayout(BorrarEditarLayout);
        BorrarEditarLayout.setHorizontalGroup(
            BorrarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorrarEditarLayout.createSequentialGroup()
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(CheckBoxDesactivar)
            .addComponent(PanelNewRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        BorrarEditarLayout.setVerticalGroup(
            BorrarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorrarEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckBoxDesactivar)
                .addGap(6, 6, 6)
                .addGroup(BorrarEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteButton)
                    .addComponent(Editar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(PanelNewRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PanelElementsLayout = new javax.swing.GroupLayout(PanelElements);
        PanelElements.setLayout(PanelElementsLayout);
        PanelElementsLayout.setHorizontalGroup(
            PanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelElementsLayout.createSequentialGroup()
                .addGroup(PanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelElementsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(106, 106, 106)
                        .addGroup(PanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(PanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelElementsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BorrarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PanelElementsLayout.setVerticalGroup(
            PanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelElementsLayout.createSequentialGroup()
                .addGroup(PanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelElementsLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(PanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6))
                    .addGroup(PanelElementsLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(PanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BorrarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelElementLayout = new javax.swing.GroupLayout(PanelElement);
        PanelElement.setLayout(PanelElementLayout);
        PanelElementLayout.setHorizontalGroup(
            PanelElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelElements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelElementLayout.setVerticalGroup(
            PanelElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelElementLayout.createSequentialGroup()
                .addComponent(PanelElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PANELS.addTab("Paquet", PanelElement);

        jTextField1.setText("jTextField1");

        CarregarDades.setText("File");

        jMenuItem2.setText("Carregar Dades");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        CarregarDades.add(jMenuItem2);

        jMenuItem3.setText("Guardar Dades");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        CarregarDades.add(jMenuItem3);

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        CarregarDades.add(jMenuItem1);

        jMenuBar1.add(CarregarDades);

        MenuHelp.setText("Help");
        MenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHelpActionPerformed(evt);
            }
        });

        Ajuda.setText("Ajuda");
        Ajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjudaActionPerformed(evt);
            }
        });
        MenuHelp.add(Ajuda);

        jMenuBar1.add(MenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANELS, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANELS, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents




    private void cpaint(Graphics g) {
        g.setColor(Color.red);
        for (int i=0;i<cp.lpunts().size();++i) {
            g.fillRect(cp.lpunts().get(i).getKey(),cp.lpunts().get(i).getValue(), 10, 10);
        }
        if (x != -1)
            g.fillRect(x, y, 10, 10);
    }     
     /**/
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void DibuixarPunts(){
         List<Map.Entry < Integer,Integer > > aux= cp.lpunts();
         if (!aux.isEmpty()){
            Graphics g2 = jPanel4.getGraphics();
            g2.setColor(Color.red);
            for (int i=1;i< aux.size();++i) {
                g2.drawLine(aux.get(i-1).getKey(),aux.get(i-1).getValue(), 
                        aux.get(i).getKey(), aux.get(i).getValue());
            }
            g2.drawLine(aux.get(aux.size()-1).getKey(),aux.get(aux.size()-1).getValue(), 
                        aux.get(0).getKey(), aux.get(0).getValue());
         }
    }
    
    private void ButtonSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSolveActionPerformed
       Graphics g3 = jPanel4.getGraphics();
       jPanel4.paint(g3);
      ArrayList<String> Elems = new ArrayList<String>();
       
      if(RadioAnnealing.isSelected()){
           boolean TwoAp2 = TwoAp.isSelected();
           boolean mut2 = MutateLittle.isSelected();
           double initTemp = Double.parseDouble(InitialTemperature.getText());
           double cool = Double.parseDouble(CoolingFactor.getText());
           int stop = Integer.parseInt(StopConditionAnealing.getText());
           double mutR = Double.parseDouble(MutationRateVar.getText());
           double mutS = Double.parseDouble(MutationSwap.getText());
           
           Elems = cp.solutionAnealing(initTemp,cool,stop,mutR,mutS,TwoAp2,mut2);
       }
       else if(RadioGenetic.isSelected()){
           boolean Roulet = Roulettesi.isSelected();
           boolean Edge = Edgesi.isSelected();
           boolean Elitism = ElitismSi.isSelected();
           int stop = Integer.parseInt(StopCondition.getText());
           int ng = Integer.parseInt(NG.getText());
           int nt = Integer.parseInt(NT.getText());
           double mr = Double.parseDouble(MutationRate.getText());
           int ts = Integer.parseInt(TournamentSize.getText());
           double ms = Double.parseDouble(MS.getText());
           int mutate = 1;
           if(Mutate1.isSelected()) mutate = 0;
           if(Mutat3.isSelected()) mutate = 3;
           Elems = cp.solutionGenetic(stop,ng,nt,mr,ts,ms,mutate,Roulet,Edge,Elitism);
           
       }
       info.setText("Solució trobada");
       if(Elems.isEmpty()) info.setText("");
       DibuixarPunts();
       cpaint(g3);
            TextSolution.setText("El Tour es : ");
            for(int i=0; i<Elems.size(); ++i) TextSolution.setText(TextSolution.getText() + Elems.get(i) + "   ");
            CostText.setText("El Cost es : " +cp.getCost());
        
        
    }//GEN-LAST:event_ButtonSolveActionPerformed

    private void SaveNewElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNewElementActionPerformed
        
        if( !NomElement.getText().isEmpty() && Relacions.size()==numRelations){
            active = true;   
           
            //afegim el punt a la vista i a la capa de domini
            cp.addPunt(x, y,NomElement.getText(),Relacions);
            
            
           actualitzarElements();
           actualitzarAdjacencies();
            
            NomElement.setText(null);
            PanelNewElement.setVisible(false);
            info.setText("Element Guardat");
            List.setListData(cp.getElementsActivats().toArray());
        }
    }//GEN-LAST:event_SaveNewElementActionPerformed
    
    private void actualitzarElements(){
    List.setListData(cp.getElementsActivats().toArray());
    }
    
    private void actualitzarElementsBorrats(String nom){    
               ElementsInactius.setText(ElementsInactius.getText() + nom + "\n");
              
           }
    
    
    private void actualitzarAdjacencies(){
        TextRelations.setText("Massa Elements");
        if(cp.getElementsActivats().size()<100){
        TextRelations.setText("");
            for(int i=0; i< cp.getElementsActivats().size(); ++i){ 
                  for(int j=0; j< cp.getElementsActivats().size(); ++j){  
                      TextRelations.setText(TextRelations.getText() + cp.GetRelations().get(i).get(j) + "  ");            
                  }
                  TextRelations.setText(TextRelations.getText() + "\n");     
             }
        }
    }
    
    private void AddRelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRelationActionPerformed
       
        if(Relacions.size()== snom){
            NumRelacions.setText("-----");
            NomElementRelacio.setText("-----");
                    
        }
        else if(Integer.parseInt(Spinner.getValue().toString()) > 0){
           String nomAnterior = " ----- ";
           System.out.println("actual -> " + actual);
           ++actual;
           
           if (numRelations > 1 && actual<ListNoms.size()) nomAnterior = ListNoms.get(actual);
           NomElementRelacio.setText(nomAnterior); 
           Relacions.add(Integer.parseInt(Spinner.getValue().toString()));
           Spinner.setValue(0);
           ProgresBar.setValue(actual*(100/numRelations));
        }
        if (ProgresBar.getValue() == 100)
            jCheckBox1.setSelected(true);
    }//GEN-LAST:event_AddRelationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
       if(activeList){ 
        if (CheckBoxDesactivar.isSelected()) {
            int size = cp.getElementsActivats().size();
            for(int i=0; i<size; ++i){
            actualitzarElementsBorrats(cp.getElementsActivats().get(i));
            }
            x = -1;
            y = -1;
            cp.resetDomini();
            actualitzarElements();
        }
        else {
            String b = List.getSelectedValue().toString();
                 actualitzarElementsBorrats(b); 
                 cp.eliminaElement(b); 
                 actualitzarAdjacencies();
                 actualitzarElements();
          }    
       PanelNewRelation.setVisible(false);
       BorrarEditar.setVisible(false); 
       }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void RadioAnnealingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioAnnealingActionPerformed
        if (RadioAnnealing.isSelected()) {
            RadioGenetic.setSelected(false);
        }
    }//GEN-LAST:event_RadioAnnealingActionPerformed

    private void RadioGeneticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioGeneticActionPerformed
        if (RadioGenetic.isSelected()) {
            RadioAnnealing.setSelected(false);
        }
    }//GEN-LAST:event_RadioGeneticActionPerformed

    private void ResetVista(){
        RadioGenetic.setSelected(false);
        RadioGenetic.setSelected(false);
        TextSolution.setText("");
        CostText.setText("");
        cp.ResetPunts();
        //PanelNewElement.setVisible(false);
       // jPanel4 = new javax.swing.JPanel();
    }
    
    private void textxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textxyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textxyActionPerformed

    private void RandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomActionPerformed
        TwoAp.setSelected(false);
    }//GEN-LAST:event_RandomActionPerformed

    private void TwoApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoApActionPerformed
        Random.setSelected(false);
    }//GEN-LAST:event_TwoApActionPerformed

    private void MutateLittleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MutateLittleActionPerformed
        MutateRate.setSelected(false);
        MutePanel.setVisible(false);
        //setVisible(true);
    }//GEN-LAST:event_MutateLittleActionPerformed

    private void MutateRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MutateRateActionPerformed
        MutateLittle.setSelected(false);
        MutePanel.setVisible(true);
    }//GEN-LAST:event_MutateRateActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       
        //System.getProperty("line.separator")
        javax.swing.JFileChooser FileChoser = new javax.swing.JFileChooser();      
        FileChoser.showOpenDialog(this);
        ResetVista();
        cp.resetDomini();
        File fil = FileChoser.getSelectedFile();
        cp.carregar_dades(fil.getAbsolutePath());
        actualitzarAdjacencies();
        actualitzarElements();
        Graphics c = jPanel4.getGraphics();
        jPanel4.paint(c);
        Cancel();
        info.setText("Fitxer Carregat");
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void Cancel(){
        Relacions = new  ArrayList<Integer>(); 
        x = -1;
        y = -1;
        PanelNewElement.setVisible(false);
        active = true;
    }
    
    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        Cancel();
        Graphics g3 = jPanel4.getGraphics();
        jPanel4.paint(g3);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        javax.swing.JFileChooser FileChoser = new javax.swing.JFileChooser();
        FileChoser.showSaveDialog(this);
        File fil = FileChoser.getSelectedFile();
        cp.guardar_dades(fil.getAbsolutePath()+ ".txt");
        info.setText("Fitxer Guardat");
       
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHelpActionPerformed
      
    }//GEN-LAST:event_MenuHelpActionPerformed

    private void AjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjudaActionPerformed
         System.out.println("holaaaaaa");
         String bar = System.getProperty("file.separator");
        String path = "src" + bar + "CapaDades" + bar + "Ajuda.pdf";
       File fil = new File(path);
       try {
          Desktop.getDesktop().open(fil);
       }
        catch (IOException ex) {}
    }//GEN-LAST:event_AjudaActionPerformed

    private void Mutat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mutat3ActionPerformed
        Mutate1.setSelected(false);
        Mutat2.setSelected(false);
    }//GEN-LAST:event_Mutat3ActionPerformed

    private void Mutat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mutat2ActionPerformed
        Mutate1.setSelected(false);
        Mutat3.setSelected(false);
    }//GEN-LAST:event_Mutat2ActionPerformed

    private void Mutate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mutate1ActionPerformed
        Mutat2.setSelected(false);
        Mutat3.setSelected(false);
    }//GEN-LAST:event_Mutate1ActionPerformed

    private void EdgenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdgenoActionPerformed
        Edgesi.setSelected(false);
    }//GEN-LAST:event_EdgenoActionPerformed

    private void EdgesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdgesiActionPerformed
        Edgeno.setSelected(false);
    }//GEN-LAST:event_EdgesiActionPerformed

    private void ElitismnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElitismnoActionPerformed
        ElitismSi.setSelected(false);
    }//GEN-LAST:event_ElitismnoActionPerformed

    private void ElitismSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElitismSiActionPerformed
        Elitismno.setSelected(false);
    }//GEN-LAST:event_ElitismSiActionPerformed

    private void RoulettenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoulettenoActionPerformed
        Roulettesi.setSelected(false);
    }//GEN-LAST:event_RoulettenoActionPerformed

    private void RoulettesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoulettesiActionPerformed
        Rouletteno.setSelected(false);
    }//GEN-LAST:event_RoulettesiActionPerformed

    private void IMAGENMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IMAGENMouseClicked
        if (active){

            Relacions = new ArrayList<Integer>();
            numRelations = cp.numElementsActius();
            ListNoms = cp.getElementsActivats();
            actual = 0;
            snom = ListNoms.size();

            for (int q=0; q<ListNoms.size(); ++q) System.out.println(ListNoms.get(q));

            System.out.println(numRelations);

            x = evt.getX();
            y = evt.getY();
            textxy.setText("xy =  " + x + "," + y);
            Graphics g2 = jPanel4.getGraphics();
            g2.setColor(Color.red);
            g2.fillRect(x, y, 10, 10);

            String as = "Cap Relació";
            if(numRelations>0) as= ListNoms.get(actual);
            //++ actual;
            NumRelacions.setText(String.valueOf(ListNoms.size()));
            if(Relacions.size()==numRelations){
                NumRelacions.setText("-----");
                NomElementRelacio.setText("----");

            }
            
            NomElementRelacio.setText(as);
            PanelNewElement.setVisible(true);
            ProgresBar.setValue(0);

        }
        active = false;
    }//GEN-LAST:event_IMAGENMouseClicked

    private void PanelPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPrincipalMouseClicked
        Graphics g22 = jPanel4.getGraphics();
        jPanel4.paint(g22);
    }//GEN-LAST:event_PanelPrincipalMouseClicked

    private void ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListMouseClicked

        BorrarEditar.setVisible(true);  
    }//GEN-LAST:event_ListMouseClicked

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        
        if(activeList){
        actualRelation = 0;
        String nom = List.getSelectedValue().toString();
        PanelNewRelation.setVisible(true);
        adjac = cp.GetRelations().get(cp.getPosicio(nom));
        
        for(int i=0; i<cp.GetRelations().size(); ++i){
            
            if(adjac.get(i) != 0 && cp.isEnabled(cp.getElements().get(i))){
                TextNewRelation.setText(cp.getElements().get(i));
                actualRelation = i;
                break;   
             }
        }
        activeList = false;
        }
    }//GEN-LAST:event_EditarActionPerformed

    private void ButtonNewRelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNewRelationActionPerformed
            int value = Integer.parseInt(SpinnerNewRelation.getValue().toString()); 
            String nom = List.getSelectedValue().toString();
            boolean f = false;
        if(value >0){
                
                
                while(actualRelation<adjac.size() && !f){ 
                    
                    int i = actualRelation;
                    if(cp.isEnabled(cp.getElements().get(i)) && cp.getElements().get(i)!=nom){
                      adjac.set(i, value);
                   
                      //xapuza
                      if(actualRelation+1 < cp.getElements().size()){
                       String nomAux = cp.getElements().get(actualRelation+1);
                       if(cp.getElements().get(actualRelation+1)==nom && actualRelation+2 < cp.getElements().size()) 
                           nomAux = cp.getElements().get(actualRelation+2);
                      //xapuza end
                      
                       TextNewRelation.setText(nomAux);
                      }
                      
                      f = true;
                }
                    ++actualRelation;
             }
         }
       if (actualRelation==adjac.size()){
           actualRelation = 0;
           PanelNewRelation.setVisible(false);
           BorrarEditar.setVisible(false);
           cp.modificarAdjacencies(nom, adjac);
           actualitzarAdjacencies();
           activeList = true;
       }
    }//GEN-LAST:event_ButtonNewRelationActionPerformed
   
    
    
    /**
     * @param args the command line arguments
     */
   public static void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRelation;
    private javax.swing.JMenuItem Ajuda;
    private javax.swing.JPanel BorrarEditar;
    private javax.swing.JButton ButtonNewRelation;
    private javax.swing.JButton ButtonSolve;
    private javax.swing.JButton CancelButton;
    private javax.swing.JMenu CarregarDades;
    private javax.swing.JCheckBox CheckBoxDesactivar;
    private javax.swing.JTextField CoolingFactor;
    private javax.swing.JTextField CostText;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JRadioButton Edgeno;
    private javax.swing.JRadioButton Edgesi;
    private javax.swing.JButton Editar;
    private javax.swing.JTextArea ElementsInactius;
    private javax.swing.JRadioButton ElitismSi;
    private javax.swing.JRadioButton Elitismno;
    private javax.swing.JLabel IMAGEN;
    private javax.swing.JTextField InitialTemperature;
    private javax.swing.JLabel Jlabel3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel LabelSeleccio;
    private javax.swing.JList List;
    private javax.swing.JTextField MS;
    private javax.swing.JMenu MenuHelp;
    private javax.swing.JRadioButton Mutat2;
    private javax.swing.JRadioButton Mutat3;
    private javax.swing.JRadioButton Mutate1;
    private javax.swing.JRadioButton MutateLittle;
    private javax.swing.JRadioButton MutateRate;
    private javax.swing.JTextField MutationRate;
    private javax.swing.JTextField MutationRateVar;
    private javax.swing.JTextField MutationSwap;
    private javax.swing.JPanel MutePanel;
    private javax.swing.JTextField NG;
    private javax.swing.JTextField NT;
    private javax.swing.JTextField NomElement;
    private javax.swing.JTextField NomElementRelacio;
    private javax.swing.JTextField NumRelacions;
    private javax.swing.JTabbedPane PANELS;
    private javax.swing.JPanel PanelElement;
    private javax.swing.JPanel PanelElements;
    private javax.swing.JPanel PanelNewElement;
    private javax.swing.JPanel PanelNewRelation;
    private javax.swing.JPanel PanelOpcions;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JProgressBar ProgresBar;
    private javax.swing.JRadioButton RadioAnnealing;
    private javax.swing.JRadioButton RadioGenetic;
    private javax.swing.JRadioButton Random;
    private javax.swing.JRadioButton Rouletteno;
    private javax.swing.JRadioButton Roulettesi;
    private javax.swing.JButton SaveNewElement;
    private javax.swing.JSpinner Spinner;
    private javax.swing.JSpinner SpinnerNewRelation;
    private javax.swing.JTextField StopCondition;
    private javax.swing.JTextField StopConditionAnealing;
    private javax.swing.JTabbedPane TabAnealing;
    private javax.swing.JTextField TextNewRelation;
    private javax.swing.JTextArea TextRelations;
    private javax.swing.JTextArea TextSolution;
    private javax.swing.JTextField TournamentSize;
    private javax.swing.JRadioButton TwoAp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JTextField info;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField textxy;
    // End of variables declaration//GEN-END:variables
}

